#! /bin/bash

docker rm -f my-mysql
docker run --name my-mysql -e MYSQL_ROOT_PASSWORD=my-mysqlpw -d mysql

# Connect to MySQL from the MySQL command line client
# docker run -it --link my-mysql:mysql --rm mysql sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'
