#! /bin/bash

ES_VERSION=2.1.0
ES_HOME=/elasticsearch

if [ ! -f elasticsearch-$ES_VERSION.tar.gz ]; then
    wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.tar.gz
    [ $? -ne 0 ] && exit 1
fi

rm -rf elasticsearch
tar xzvf elasticsearch-$ES_VERSION.tar.gz
[ $? -ne 0 ] && exit 1
mv elasticsearch-$ES_VERSION elasticsearch
[ $? -ne 0 ] && exit 1

echo -e "cluster.name: elastic" > elasticsearch.yml
echo -e "path.logs: $ES_HOME/data/log" >> elasticsearch.yml
echo -e "path.data: $ES_HOME/data" >> elasticsearch.yml
echo -e "network.host: 0" >> elasticsearch.yml
echo -e "discovery.zen.ping.multicast.enable: true" >> elasticsearch.yml

docker build -t elastic .
