MYLIB=$(shell pwd |sed 's/\(.*mylibrary\).*/\1/')

LIB=$(MYLIB)/lib
INC=$(MYLIB)/utils
UTILS=$(MYLIB)/utils

prefix = /usr/local
libdir = ${prefix}/lib
bindir = ${prefix}/bin
sbindir= ${prefix}/sbin
etcdir = ${prefix}/etc
mandir = ${prefix}/share/man

CC=gcc
CXX=g++
INSTALL=install
