MYLIBRARY=$(shell pwd |sed 's/\(.*mylibrary\).*/\1/')

LIB=$(MYLIBRARY)/lib
INC=$(MYLIBRARY)/utils
UTILS=$(MYLIBRARY)/utils

prefix = /usr/local
bindir = ${exec_prefix}/bin
sbindir= ${exec_prefix}/sbin
etcdir = ${prefix}/etc
mandir = ${prefix}/share/man

CC=gcc
CXX=g++
INSTALL=install
