#! /bin/bash

HOST=$1
PORT=$2

if [ -z "$HOST" ]; then
    HOST=localhost
fi
if [ -z "$PORT" ]; then
    PORT=3200
fi

CLIENT="./client -h $HOST -p $PORT "

while true
do
  $CLIENT < server.c 
  usleep 100000
done