#! /bin/bash

cwd=$(pwd)

function build_client() {
    cd rabbitmq-c
    mkdir -p build
    cd build && rm -rf *
    cmake -DCMAKE_INSTALL_PREFIX=$cwd -DCMAKE_INSTALL_LIBDIR=$cwd -DCMAKE_INSTALL_INCLUDEDIR=$cwd  ..
    [ $? -ne 0 ] && echo "cmake error" && exit 1
    make
    [ $? -ne 0 ] && echo "make error" && exit 1

    cp librabbitmq/librabbitmq.a $cwd/
}

if [ ! -d rabbitmq-c ]; then
    git clone git@github.com:alanxz/rabbitmq-c.git
    [ $? -ne 0 ] && echo "download error" && exit 1
    build_client
fi

cd $cwd
ln -f ~/tmp/depot/AppID/urlparser.c urlparser.c

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
